#!/bin/sh
set -ex
PKG_TOPDIR=$(cd $(dirname $0) && pwd -P)
PKG_NAME=libmaxminddb
PKG_VERSION=1.3.2
PKG_CHECKSUM=e6f881aa6bd8cfa154a44d965450620df1f714c6dc9dd9971ad98f6e04f6c0f0
PKG_URL=https://github.com/maxmind/libmaxminddb/releases/download/$PKG_VERSION/$PKG_NAME-$PKG_VERSION.tar.gz
PKG_BUILD=2
[ "$PKG_OS" != "" -a "$PKG_ARCH" != "" ]
PKG_FULLNAME=$PKG_NAME/$PKG_VERSION-$PKG_BUILD
PKG_BUILDDIR=$PKG_TOPDIR/MK_BUILD/$PKG_OS/$PKG_FULLNAME/$PKG_ARCH
rm -rf $PKG_BUILDDIR
install -d $PKG_BUILDDIR
(
  set -ex
  cd $PKG_BUILDDIR
  curl -fsSLO --progress-bar $PKG_URL
  REAL_CHECKSUM=$(cmake.exe -E sha256sum $PKG_NAME-$PKG_VERSION.tar.gz | awk '{print $1}')
  [ $PKG_CHECKSUM = "$REAL_CHECKSUM" ]
  cmake.exe -E tar -xzf $PKG_NAME-$PKG_VERSION.tar.gz
  cd $PKG_NAME-$PKG_VERSION
  PKG_INSTALLDIR=$PKG_TOPDIR/MK_DIST/$PKG_OS/$PKG_FULLNAME/$PKG_ARCH
  rm -rf $PKG_INSTALLDIR
  install -d $PKG_INSTALLDIR/include
  install -d $PKG_INSTALLDIR/lib
  cd projects/VS12
  if [ "$PKG_ARCH" = "x86" ]; then
    PLATFORM=Win32
    ARCH_DIR=""
  elif [ "$PKG_ARCH" = "x64" ]; then
    PLATFORM=$PKG_ARCH
    ARCH_DIR="x64/"
  else
    echo "Unexpected PKG_ARCH: $PKG_ARCH" 1>&2
    exit 1
  fi
  msbuild.exe /p:Configuration=release /p:Platform=$PLATFORM /p:PlatformToolset=v141 /p:WindowsTargetPlatformVersion=$UCRTVersion /t:libmaxminddb
  cp ${ARCH_DIR}Release/libmaxminddb.lib $PKG_INSTALLDIR/lib/maxminddb.lib
  cp ../../include/maxminddb_config.h $PKG_INSTALLDIR/include
  cp ../../include/maxminddb.h $PKG_INSTALLDIR/include
)
