#!/bin/sh
set -ex
PKG_TOPDIR=$(cd $(dirname $0) && pwd -P)
cd $PKG_TOPDIR
PKG_NAME=libressl
PKG_VERSION=2.7.4
PKG_CHECKSUM=1e3a9fada06c1c060011470ad0ff960de28f9a0515277d7336f7e09362517da6
PKG_URL=https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/$PKG_NAME-$PKG_VERSION.tar.gz
PKG_BUILD=1
[ "$PKG_OS" != "" -a "$PKG_ARCH" != "" ]
PKG_FULLNAME=$PKG_NAME/$PKG_VERSION-$PKG_BUILD
PKG_BUILDDIR=$PKG_TOPDIR/MK_BUILD/$PKG_OS/$PKG_FULLNAME/$PKG_ARCH
rm -rf $PKG_BUILDDIR
install -d $PKG_BUILDDIR
(
  set -ex
  cd $PKG_BUILDDIR
  curl -LO --progress-bar $PKG_URL
  REAL_CHECKSUM=$(cmake.exe -E sha256sum $PKG_NAME-$PKG_VERSION.tar.gz | awk '{print $1}')
  [ $PKG_CHECKSUM = "$REAL_CHECKSUM" ]
  cmake.exe -E tar -xzf $PKG_NAME-$PKG_VERSION.tar.gz
  cd $PKG_NAME-$PKG_VERSION
  PKG_INSTALLDIR=../../../../../../MK_DIST/$PKG_OS/$PKG_FULLNAME/$PKG_ARCH
  rm -rf $PKG_INSTALLDIR
  install -d $PKG_INSTALLDIR
  cmake.exe -G "NMake Makefiles" -DBUILD_SHARED=OFF                            \
          -DCMAKE_INSTALL_PREFIX="$PKG_INSTALLDIR"                             \
          -DCMAKE_BUILD_TYPE=Release
  nmake.exe /f Makefile install
  rm -rf $PKG_INSTALLDIR/bin
  rm -rf $PKG_INSTALLDIR/etc
  rm -rf $PKG_INSTALLDIR/include/CMakeFiles
  rm -rf $PKG_INSTALLDIR/include/*.cmake
  rm -rf $PKG_INSTALLDIR/lib/*.dll
  rm -rf $PKG_INSTALLDIR/lib/*-*.lib
  rm -rf $PKG_INSTALLDIR/share
)
